# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\design\ui\cart.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CothesStoreCart(object):
    def setupUi(self, CothesStoreCart):
        CothesStoreCart.setObjectName("CothesStoreCart")
        CothesStoreCart.resize(600, 403)
        self.centralwidget = QtWidgets.QWidget(CothesStoreCart)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topLayout = QtWidgets.QHBoxLayout()
        self.topLayout.setObjectName("topLayout")
        self.backBtn = QtWidgets.QPushButton(self.centralwidget)
        self.backBtn.setMinimumSize(QtCore.QSize(40, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.backBtn.setFont(font)
        self.backBtn.setObjectName("backBtn")
        self.topLayout.addWidget(self.backBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.topLayout.addItem(spacerItem)
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(36)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.titleLabel.setFont(font)
        self.titleLabel.setStyleSheet("font: 36pt \"MS Shell Dlg 2\";")
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.topLayout.addWidget(self.titleLabel, 0, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.topLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.topLayout)
        self.clothesScrollArea = QtWidgets.QScrollArea(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.clothesScrollArea.setFont(font)
        self.clothesScrollArea.setWidgetResizable(True)
        self.clothesScrollArea.setObjectName("clothesScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 580, 252))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.itemsLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.itemsLayout.setObjectName("itemsLayout")
        self.clothesList = QtWidgets.QVBoxLayout()
        self.clothesList.setObjectName("clothesList")
        self.itemsLayout.addLayout(self.clothesList)
        self.clothesScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.clothesScrollArea)
        self.totalPrice = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.totalPrice.setFont(font)
        self.totalPrice.setObjectName("totalPrice")
        self.verticalLayout.addWidget(self.totalPrice)
        self.orderBtn = QtWidgets.QPushButton(self.centralwidget)
        self.orderBtn.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.orderBtn.setFont(font)
        self.orderBtn.setObjectName("orderBtn")
        self.verticalLayout.addWidget(self.orderBtn)
        CothesStoreCart.setCentralWidget(self.centralwidget)

        self.retranslateUi(CothesStoreCart)
        QtCore.QMetaObject.connectSlotsByName(CothesStoreCart)

    def retranslateUi(self, CothesStoreCart):
        _translate = QtCore.QCoreApplication.translate
        CothesStoreCart.setWindowTitle(_translate("CothesStoreCart", "Корзина книжного магазина"))
        self.backBtn.setText(_translate("CothesStoreCart", "◀ Назад"))
        self.titleLabel.setText(_translate("CothesStoreCart", "Ваша корзина"))
        self.totalPrice.setText(_translate("CothesStoreCart", "Общая стоимость: 0 ₽"))
        self.orderBtn.setText(_translate("CothesStoreCart", "Оформить заказ"))
